export const queryKeys = {
  product: {
    list: "productAll",
    cart: "productCart",
    best: "productBest",
    home: "productHome",
    count: "inquiryCount",
    review: "productReview",
    detail: "productDetail",
    search: "productSearch",
    inquiry: "productInquiry",
    homeMore: "productHomeMore",
    favorite: "productFavorite",
    recommend: "productRecommend",
    orderForm: "productOrderForm",
  },
  mypage: {
    qa: "qa",
    my: "myInfo",
    review: "review",
    order: "myOrder",
    claim: "myClaim",
    inquiry: "inquiry",
    counsel: "myCounsel",
    unReview: "unReview",
    existNick: "existNickname",
    orderDetail: "orderDetail",
    purchaseCount: "purchaseCount",
  },
  enums: {
    inquiry: "enumsInquiryState",
    cancelReason: "enumsCancelReason",
    returnReason: "enumsReturnReason",
  },
  search: {
    best: "searchBest",
    product: "searchProduct",
    recommend: "searchRecommend",
  },
};
